version: "3.7"

services:
  nginx:
    container_name: cake-nginx
    build:
      context: ./config/nginx/
      dockerfile: Dockerfile
    volumes:
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./source:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - php
      - mysql
    links:
      - php

  php:
    container_name: cake-php
    build:
      context: ./config/php/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "./source:/var/www/html"
      - "./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USERE: root
      PMA_PASSWORD: root
    links:
      - mysql

  mysql:
    container_name: cake-mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/data:/var/lib/mysql